In [1]:
import numpy as np

In [11]:
array1D = np.arange(1,9)
print(array1D)

[1 2 3 4 5 6 7 8]


In [14]:
array3D = array1D.reshape(2,2,2)
print(array3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
array2D = array3D.reshape(4,2)
print(array2D)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [22]:
arrayUn = array1D.reshape(2,2,-1)
print(arrayUn)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
flat = arrayUn.reshape(-1)
print(flat)

[1 2 3 4 5 6 7 8]


In [38]:
# a = np.array([0,4,8,12])
# b = np.array([[1,2,3,4],[5,6,7,8]])
# # c = np.add(a,b)
# # d = np.subtract(a,b)
# # e = np.multiply(a,b)
# # f = np.divide(a,b)
# g = np.power(b,a)
# g

In [50]:
# test = np.array([i for i in range(10)])
# test2 = np.where(test%2==0,(test+1),(test-1))
# conditions = [test<3,test < 6, test>6]
# actions = [test*0, test*2, test-1]
# test3 = np.select(conditions, actions,default=test)

array([ 0,  0,  0,  6,  8, 10,  6,  6,  7,  8])

In [52]:
test = np.array([i for i in range(4,10)])
minimum = np.amin(test)
minimum

4